# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T1_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strName', models.CharField(max_length=20)),
                ('strType', models.CharField(max_length=20)),
                ('nTaskID', models.IntegerField(default=0)),
                ('nStatus', models.IntegerField(default=2)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='T2_MoneyApplyFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTaskID', models.IntegerField()),
                ('nStatus', models.IntegerField(default=1)),
                ('nMoney', models.IntegerField(default=0)),
                ('strNode', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='T2_TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTaskID', models.IntegerField()),
                ('nStatus', models.IntegerField(default=1)),
                ('nMoney', models.IntegerField(default=0)),
                ('strNode', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
